### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by tuler** [ensody/ssh-agent-inject#2]
During a docker build which requires a RUN with `--mount=type=ssh`, I end up with the error below printed by ssh-agent-inject process.

`Error fetching containers error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.25/containers/json?filters=%7B%22label%22%3A%7B%22com.ensody.ssh-agent-inject%22%3Atrue%7D%7D&limit=0: dial unix /var/run/docker.sock: socket: too many open files`

**Comment by wkornewald** [comment]
Thanks for the bug report. Indeed, I didn't close the Docker socket, so ssh-agent-inject was consuming more and more resources over time. Should be fixed in v0.9.1 to be released in a few minutes.
